In [3]:
import numpy as np
house = np.array([4,0,2,20.2])
print(house)
print(house.shape)

[ 4.   0.   2.  20.2]
(4,)


In [4]:
X = np.array([
    [4, 2],
    [2, 1],
    [10.2, 4]
])                  # representation of metrices using numpy
print(X)
print(X.shape)

[[ 4.   2. ]
 [ 2.   1. ]
 [10.2  4. ]]
(3, 2)


In [9]:
X = np.array([[4, 1, 4.7], [3, 2, 9.2]])
print(X)
print(X.shape)
X.T

[[4.  1.  4.7]
 [3.  2.  9.2]]
(2, 3)


array([[4. , 3. ],
       [1. , 2. ],
       [4.7, 9.2]])

In [11]:
# scalar multiplication using numpy
X = np.array([
    [4, 2],
    [2, 1],
    [10.2, 4]
]) 
print("X = ",X)
print("Shape of X metrics ---> ",X.shape)

b = np.array([1, 1, 0.4])
print("b =",b)
print("Shape of b vector --->",b.shape) 
print("Dot product using 'np.dot' --->",np.dot(X.T, b)) #

print("Dot product using '.dot' --->",X.T.dot(b))

print("Dot product using '@' --->",X.T @ b)
print((X.T @ b).shape)

X =  [[ 4.   2. ]
 [ 2.   1. ]
 [10.2  4. ]]
Shape of X metrics --->  (3, 2)
b = [1.  1.  0.4]
Shape of b vector ---> (3,)
Dot product using 'np.dot' ---> [10.08  4.6 ]
Dot product using '.dot' ---> [10.08  4.6 ]
Dot product using '@' ---> [10.08  4.6 ]
(2,)


In [15]:
list_number = [1,2,3]
newList = [i**2 for i in list_number if i==2]
newList

[4]

In [18]:
u = np.array([1,3])
import numpy.linalg as LA
LA.norm(u)

np.float64(3.1622776601683795)